import Layout from "../components/Layout";
import Head from "next/head";
import Navbar from "@/components/navbar/navbar";
import Carousal from "@/components/carousal/carousal";
import Pizzalist from "@/components/Pizzalist";
import Footer from "@/components/footer/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pizza Restaurant in Newyork</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousal />
      <Pizzalist />
    </>
  );
}
